export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/1.jpeg",
    username: "황상한",
  },
  {
    id: 2,
    profilePicture: "assets/person/2.jpeg",
    username: "신태수",
  },
  {
    id: 3,
    profilePicture: "assets/person/3.jpeg",
    username: "홍순명",
  },
  {
    id: 4,
    profilePicture: "assets/person/4.jpeg",
    username: "황진영",
  },
  {
    id: 5,
    profilePicture: "assets/person/5.jpeg",
    username: "김현수",
  },
  {
    id: 6,
    profilePicture: "assets/person/6.jpeg",
    username: "홍진혁",
  },
  {
    id: 7,
    profilePicture: "assets/person/7.jpeg",
    username: "임보람",
  },
  {
    id: 8,
    profilePicture: "assets/person/8.jpeg",
    username: "이은비",
  },
  {
    id: 9,
    profilePicture: "assets/person/9.jpeg",
    username: "이설련",
  },
  {
    id: 10,
    profilePicture: "assets/person/10.jpeg",
    username: "박송원",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "오늘 교대역 퇴근길 감성 ㅋㅋㅋㅋ",
    photo: "assets/post/1.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    photo: "오늘 삼성역 출근길 감성 ㅋㅋㅋ",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 1,
  },
  {
    id: 3,
    desc: "오늘 강남역 출근길 감성 ㅋㅋㅋ",
    photo: "assets/post/3.jpeg",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 2,
  },
  {
    id: 4,
    photo: "assets/post/4.jpeg",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 3,
  },
  {
    id: 5,
    photo: "assets/post/5.jpeg",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 5,
  },
  {
    id: 6,
    photo: "assets/post/6.jpeg",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 6,
  },
  {
    id: 7,
    desc: "오늘 방배역 출근길 감성 ㅋㅋㅋ",
    photo: "assets/post/7.jpeg",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 3,
  },
  {
    id: 8,
    photo: "assets/post/8.jpeg",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 1,
  },
  {
    id: 9,
    desc: "오늘 의정부역 출근길 감성 ㅋㅋㅋ",
    photo: "assets/post/9.jpeg",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 2,
  },
  {
    id: 10,
    photo: "assets/post/10.jpeg",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 12,
  },
];
